spring:
  application:
    name: mcpserver
  ai:
    mcp:
      server:
        name: test
        version: 0.1.1
        protocol: streamable
        stdio: false
        type: sync

aviationstack:
  api-key: test